"""Make working_document task_id nullable

Revision ID: 3cda7b5e51f6
Revises: 95a7b3c8391e
Create Date: 2026-03-20 05:09:37.660798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cda7b5e51f6'
down_revision: Union[str, Sequence[str], None] = '95a7b3c8391e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('working_documents', 'task_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('working_documents', 'task_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
