"""Add venue_id to working_documents, hiring_criteria, jobs, automated_tasks

Revision ID: 3da021bb30c3
Revises: ebed686ee962
Create Date: 2026-03-20 23:15:45.873311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3da021bb30c3'
down_revision: Union[str, Sequence[str], None] = 'ebed686ee962'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('automated_tasks', sa.Column('venue_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'automated_tasks', 'venues', ['venue_id'], ['id'])
    op.add_column('hiring_criteria', sa.Column('venue_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'hiring_criteria', 'venues', ['venue_id'], ['id'])
    op.add_column('jobs', sa.Column('venue_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'jobs', 'venues', ['venue_id'], ['id'])
    op.add_column('working_documents', sa.Column('venue_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'working_documents', 'venues', ['venue_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'working_documents', type_='foreignkey')
    op.drop_column('working_documents', 'venue_id')
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_column('jobs', 'venue_id')
    op.drop_constraint(None, 'hiring_criteria', type_='foreignkey')
    op.drop_column('hiring_criteria', 'venue_id')
    op.drop_constraint(None, 'automated_tasks', type_='foreignkey')
    op.drop_column('automated_tasks', 'venue_id')
    # ### end Alembic commands ###
