"""add session_id to tasks

Revision ID: 5f13308a845f
Revises: 1968069b07a2
Create Date: 2026-03-14 03:00:12.395389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f13308a845f'
down_revision: Union[str, Sequence[str], None] = '1968069b07a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('session_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_tasks_session_id'), 'tasks', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_session_id'), table_name='tasks')
    op.drop_column('tasks', 'session_id')
    # ### end Alembic commands ###
