"""add_roles_table_and_permissions

Revision ID: 6d95321ad9e6
Revises: 7ee00ad9684f
Create Date: 2026-03-25 01:06:00.861069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import json
import uuid
from datetime import datetime, timezone


# revision identifiers, used by Alembic.
revision: str = '6d95321ad9e6'
down_revision: Union[str, Sequence[str], None] = '7ee00ad9684f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Standard role definitions (must match app/auth/permissions.py)
_STANDARD_ROLES = {
    "owner": {
        "display_name": "Owner",
        "description": "Full access to everything in the organization.",
    },
    "manager": {
        "display_name": "Manager",
        "description": "Manage day-to-day operations. Cannot change billing or create custom roles.",
    },
    "team_member": {
        "display_name": "Team Member",
        "description": "View data and create tasks. Read-only access to most areas.",
    },
    "payroll_admin": {
        "display_name": "Payroll Administrator",
        "description": "Manage HR, roster, and employee data.",
    },
}

# Map old membership role strings to new system role names
_ROLE_MIGRATION_MAP = {
    "owner": "owner",
    "admin": "manager",
    "member": "team_member",
}


def upgrade() -> None:
    """Upgrade schema."""
    # 1. Create roles table
    op.create_table('roles',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('organization_id', sa.String(), nullable=True),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('display_name', sa.String(), nullable=False),
        sa.Column('description', sa.String(), nullable=True),
        sa.Column('is_system', sa.Boolean(), nullable=False),
        sa.Column('permissions', sa.JSON(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['organization_id'], ['organizations.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('organization_id', 'name', name='uq_org_role_name'),
    )

    # 2. Add role_id column to organization_memberships
    op.add_column('organization_memberships', sa.Column('role_id', sa.String(), nullable=True))
    op.create_foreign_key('fk_membership_role', 'organization_memberships', 'roles', ['role_id'], ['id'])

    # 3. Seed system roles (import permissions here to get actual permission lists)
    from app.auth.permissions import STANDARD_ROLES

    now = datetime.now(timezone.utc)
    conn = op.get_bind()
    role_ids = {}

    for name, defn in STANDARD_ROLES.items():
        role_id = str(uuid.uuid4())
        role_ids[name] = role_id
        conn.execute(
            sa.text(
                "INSERT INTO roles (id, organization_id, name, display_name, description, is_system, permissions, created_at, updated_at) "
                "VALUES (:id, NULL, :name, :display_name, :description, TRUE, :permissions, :now, :now)"
            ),
            {
                "id": role_id,
                "name": name,
                "display_name": defn["display_name"],
                "description": defn["description"],
                "permissions": json.dumps(defn["permissions"]),
                "now": now,
            },
        )

    # 4. Migrate existing memberships to use role_id
    for old_role, new_role_name in _ROLE_MIGRATION_MAP.items():
        new_role_id = role_ids[new_role_name]
        conn.execute(
            sa.text(
                "UPDATE organization_memberships SET role_id = :role_id WHERE role = :old_role"
            ),
            {"role_id": new_role_id, "old_role": old_role},
        )

    # 5. Rename User.role "manager" → "user" (platform-level role)
    conn.execute(
        sa.text("UPDATE users SET role = 'user' WHERE role = 'manager'")
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'organization_memberships', type_='foreignkey')
    op.drop_column('organization_memberships', 'role_id')
    op.drop_table('roles')
    # ### end Alembic commands ###
