"""add_slimmed_content_to_tool_calls

Revision ID: 7ee00ad9684f
Revises: a1b2c3d4e5f6
Create Date: 2026-03-24 22:16:37.320384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ee00ad9684f'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_approvals_task_id'), table_name='approvals')
    op.drop_index(op.f('ix_automated_task_runs_automated_task_id'), table_name='automated_task_runs')
    op.drop_index(op.f('ix_deployments_environment'), table_name='deployments')
    op.drop_index(op.f('ix_e2e_test_runs_environment'), table_name='e2e_test_runs')
    op.drop_index(op.f('ix_e2e_test_runs_test_id'), table_name='e2e_test_runs')
    op.drop_index(op.f('ix_llm_calls_task_id'), table_name='llm_calls')
    op.drop_index(op.f('ix_messages_task_id'), table_name='messages')
    op.drop_index(op.f('ix_orders_task_id'), table_name='orders')
    op.drop_index(op.f('ix_tasks_venue_id'), table_name='tasks')
    op.add_column('tool_calls', sa.Column('slimmed_content', sa.Text(), nullable=True))
    op.drop_index(op.f('ix_tool_calls_connector_name'), table_name='tool_calls')
    op.drop_index(op.f('ix_tool_calls_task_id'), table_name='tool_calls')
    op.drop_index(op.f('ix_working_documents_venue_id'), table_name='working_documents')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_working_documents_venue_id'), 'working_documents', ['venue_id'], unique=False)
    op.create_index(op.f('ix_tool_calls_task_id'), 'tool_calls', ['task_id'], unique=False)
    op.create_index(op.f('ix_tool_calls_connector_name'), 'tool_calls', ['connector_name'], unique=False)
    op.drop_column('tool_calls', 'slimmed_content')
    op.create_index(op.f('ix_tasks_venue_id'), 'tasks', ['venue_id'], unique=False)
    op.create_index(op.f('ix_orders_task_id'), 'orders', ['task_id'], unique=False)
    op.create_index(op.f('ix_messages_task_id'), 'messages', ['task_id'], unique=False)
    op.create_index(op.f('ix_llm_calls_task_id'), 'llm_calls', ['task_id'], unique=False)
    op.create_index(op.f('ix_e2e_test_runs_test_id'), 'e2e_test_runs', ['test_id'], unique=False)
    op.create_index(op.f('ix_e2e_test_runs_environment'), 'e2e_test_runs', ['environment'], unique=False)
    op.create_index(op.f('ix_deployments_environment'), 'deployments', ['environment'], unique=False)
    op.create_index(op.f('ix_automated_task_runs_automated_task_id'), 'automated_task_runs', ['automated_task_id'], unique=False)
    op.create_index(op.f('ix_approvals_task_id'), 'approvals', ['task_id'], unique=False)
    # ### end Alembic commands ###
