"""add_task_context_fields_to_automated_tasks

Revision ID: 864ffb211684
Revises: c208e9f0d333
Create Date: 2026-03-25 21:02:16.378087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '864ffb211684'
down_revision: Union[str, Sequence[str], None] = 'c208e9f0d333'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('automated_task_runs', sa.Column('task_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'automated_task_runs', 'tasks', ['task_id'], ['id'])
    op.add_column('automated_tasks', sa.Column('task_config', sa.JSON(), nullable=False, server_default='{}'))
    op.add_column('automated_tasks', sa.Column('thread_summary', sa.Text(), nullable=True))
    op.add_column('automated_tasks', sa.Column('overrides_next_run', sa.JSON(), nullable=True))
    op.add_column('automated_tasks', sa.Column('conversation_task_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'automated_tasks', 'tasks', ['conversation_task_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'automated_tasks', type_='foreignkey')
    op.drop_column('automated_tasks', 'conversation_task_id')
    op.drop_column('automated_tasks', 'overrides_next_run')
    op.drop_column('automated_tasks', 'thread_summary')
    op.drop_column('automated_tasks', 'task_config')
    op.drop_constraint(None, 'automated_task_runs', type_='foreignkey')
    op.drop_column('automated_task_runs', 'task_id')
    # ### end Alembic commands ###
