"""Add venue_id to tasks and tool_calls

Revision ID: 8b11bca689f8
Revises: 3da021bb30c3
Create Date: 2026-03-20 23:27:33.655162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b11bca689f8'
down_revision: Union[str, Sequence[str], None] = '3da021bb30c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('venue_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'venues', ['venue_id'], ['id'])
    op.add_column('tool_calls', sa.Column('venue_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'tool_calls', 'venues', ['venue_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tool_calls', type_='foreignkey')
    op.drop_column('tool_calls', 'venue_id')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'venue_id')
    # ### end Alembic commands ###
