"""add_billing_tables_subscription_topup_events

Revision ID: a8e44165d3c0
Revises: a8c01c4302a0
Create Date: 2026-03-21 03:56:15.872199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8e44165d3c0'
down_revision: Union[str, Sequence[str], None] = 'a8c01c4302a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('stripe_event_id', sa.String(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('stripe_customer_id', sa.String(), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(), nullable=True),
    sa.Column('token_plan', sa.String(), nullable=False),
    sa.Column('token_quota', sa.Integer(), nullable=False),
    sa.Column('billing_cycle_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('payment_method_last4', sa.String(), nullable=True),
    sa.Column('payment_method_brand', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id'),
    sa.UniqueConstraint('stripe_customer_id'),
    sa.UniqueConstraint('stripe_subscription_id')
    )
    op.create_table('token_top_ups',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('tokens', sa.Integer(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('stripe_payment_intent_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('purchased_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['purchased_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('organizations', sa.Column('hr_agent_enabled', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('organizations', sa.Column('procurement_agent_enabled', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('organizations', sa.Column('reports_agent_enabled', sa.Boolean(), nullable=False, server_default='true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'reports_agent_enabled')
    op.drop_column('organizations', 'procurement_agent_enabled')
    op.drop_column('organizations', 'hr_agent_enabled')
    op.drop_table('token_top_ups')
    op.drop_table('subscriptions')
    op.drop_table('billing_events')
    # ### end Alembic commands ###
