"""add_unique_constraint_billing_event_stripe_id

Revision ID: af26f8c66fb9
Revises: a8e44165d3c0
Create Date: 2026-03-21 05:44:18.135844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af26f8c66fb9'
down_revision: Union[str, Sequence[str], None] = 'a8e44165d3c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'billing_events', ['stripe_event_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'billing_events', type_='unique')
    # ### end Alembic commands ###
