"""add_tags_column_to_tasks

Revision ID: b40fcd1e0b8f
Revises: 864ffb211684
Create Date: 2026-03-26 21:22:24.362420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b40fcd1e0b8f'
down_revision: Union[str, Sequence[str], None] = '864ffb211684'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1. Add tags column with empty array default
    op.add_column('tasks', sa.Column('tags', sa.JSON(), nullable=False, server_default='[]'))

    # 2. Migrate existing status values to tags
    conn = op.get_bind()
    status_to_tags = {
        "awaiting_approval": '["approval_required"]',
        "awaiting_tool_approval": '["approval_required"]',
        "awaiting_user_input": '["needs_input"]',
        "needs_clarification": '["needs_input"]',
        "submitted": '["submitted"]',
        "rejected": '["rejected"]',
    }
    for status, tags_json in status_to_tags.items():
        conn.execute(
            sa.text("UPDATE tasks SET tags = :tags WHERE status = :status"),
            {"tags": tags_json, "status": status},
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'tags')
    # ### end Alembic commands ###
