"""add_email_system_tables_and_user_id_to_oauth

Revision ID: c208e9f0d333
Revises: 6d95321ad9e6
Create Date: 2026-03-25 03:27:04.384908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c208e9f0d333'
down_revision: Union[str, Sequence[str], None] = '6d95321ad9e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_templates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('subject_template', sa.String(), nullable=False),
    sa.Column('html_template', sa.Text(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('email_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=True),
    sa.Column('venue_id', sa.String(), nullable=True),
    sa.Column('task_id', sa.String(), nullable=True),
    sa.Column('sender_type', sa.String(), nullable=False),
    sa.Column('sender_email', sa.String(), nullable=False),
    sa.Column('sender_user_id', sa.String(), nullable=True),
    sa.Column('to_addresses', sa.JSON(), nullable=False),
    sa.Column('cc_addresses', sa.JSON(), nullable=True),
    sa.Column('bcc_addresses', sa.JSON(), nullable=True),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('template_name', sa.String(), nullable=True),
    sa.Column('html_body', sa.Text(), nullable=True),
    sa.Column('has_attachments', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('provider_message_id', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['sender_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('connector_configs', sa.Column('user_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'connector_configs', 'users', ['user_id'], ['id'])
    op.add_column('oauth_states', sa.Column('user_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'oauth_states', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'oauth_states', type_='foreignkey')
    op.drop_column('oauth_states', 'user_id')
    op.drop_constraint(None, 'connector_configs', type_='foreignkey')
    op.drop_column('connector_configs', 'user_id')
    op.drop_table('email_logs')
    op.drop_table('email_templates')
    # ### end Alembic commands ###
