"""add_timezone_to_venues

Revision ID: d33b87cfd58b
Revises: d47dbb032df2
Create Date: 2026-03-22 20:14:14.871995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd33b87cfd58b'
down_revision: Union[str, Sequence[str], None] = 'd47dbb032df2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('timezone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'timezone')
    # ### end Alembic commands ###
