"""Add multi-venue architecture: organizations, memberships, venue access, per-venue connector configs

Revision ID: ebed686ee962
Revises: f3f94ddfff2d
Create Date: 2026-03-20 20:43:09.251873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebed686ee962'
down_revision: Union[str, Sequence[str], None] = 'f3f94ddfff2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('billing_email', sa.String(), nullable=True),
    sa.Column('plan', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('organization_memberships',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'organization_id', name='uq_user_org')
    )
    op.create_table('user_venue_access',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('venue_id', sa.String(), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'venue_id', name='uq_user_venue')
    )
    op.add_column('connector_configs', sa.Column('venue_id', sa.String(), nullable=True))
    op.drop_constraint(op.f('connector_configs_connector_name_key'), 'connector_configs', type_='unique')
    op.create_unique_constraint('uq_connector_venue', 'connector_configs', ['connector_name', 'venue_id'])
    op.create_foreign_key(None, 'connector_configs', 'venues', ['venue_id'], ['id'])
    op.add_column('oauth_states', sa.Column('venue_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'oauth_states', 'venues', ['venue_id'], ['id'])
    op.add_column('venues', sa.Column('organization_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'venues', 'organizations', ['organization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'venues', type_='foreignkey')
    op.drop_column('venues', 'organization_id')
    op.drop_constraint(None, 'oauth_states', type_='foreignkey')
    op.drop_column('oauth_states', 'venue_id')
    op.drop_constraint(None, 'connector_configs', type_='foreignkey')
    op.drop_constraint('uq_connector_venue', 'connector_configs', type_='unique')
    op.create_unique_constraint(op.f('connector_configs_connector_name_key'), 'connector_configs', ['connector_name'], postgresql_nulls_not_distinct=False)
    op.drop_column('connector_configs', 'venue_id')
    op.drop_table('user_venue_access')
    op.drop_table('organization_memberships')
    op.drop_table('organizations')
    # ### end Alembic commands ###
