"""Add thinking_steps column to tasks

Revision ID: f572ad8d12be
Revises: m1a2b3c4d5e6
Create Date: 2026-03-18 00:58:31.685306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f572ad8d12be'
down_revision: Union[str, Sequence[str], None] = 'm1a2b3c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('thinking_steps', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'thinking_steps')
    # ### end Alembic commands ###
